### ISSUE TITLE
Error when create a new Folder

### ISSUE THREAD

**Issue by rdp77** [tomatophp/filament-media-manager#26]
Log

~~~
[2024-11-15 08:42:12] local.ERROR: could not find driver (Connection: , SQL: select "label", "name" from "icons" limit 10) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (Connection: , SQL: select \"label\", \"name\" from \"icons\" limit 10) at /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run()
#2 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3132): Illuminate\\Database\\Connection->select()
#3 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3389): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3705): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3385): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(939): Illuminate\\Database\\Query\\Builder->pluck()
#7 /home/rdp77/Projects/laravel-filament/vendor/tomatophp/filament-icons/src/Components/IconPicker.php(21): Illuminate\\Database\\Eloquent\\Builder->pluck()
#8 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Components/ComponentManager.php(102): TomatoPHP\\FilamentIcons\\Components\\IconPicker->setUp()
#9 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Concerns/Configurable.php(22): Filament\\Support\\Components\\ComponentManager->configure()
#10 /home/rdp77/Projects/laravel-filament/vendor/filament/forms/src/Components/Field.php(27): Filament\\Support\\Components\\Component->configure()
#11 /home/rdp77/Projects/laravel-filament/vendor/tomatophp/filament-media-manager/src/Resources/FolderResource.php(85): Filament\\Forms\\Components\\Field::make()
#12 /home/rdp77/Projects/laravel-filament/vendor/filament/filament/src/Resources/Pages/ListRecords.php(99): TomatoPHP\\FilamentMediaManager\\Resources\\FolderResource::form()
#13 /home/rdp77/Projects/laravel-filament/vendor/filament/filament/src/Resources/Pages/ListRecords.php(115): Filament\\Resources\\Pages\\ListRecords->form()
#14 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Concerns/EvaluatesClosures.php(35): Filament\\Resources\\Pages\\ListRecords->Filament\\Resources\\Pages\\{closure}()
#15 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/HasForm.php(55): Filament\\Support\\Components\\Component->evaluate()
#16 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(286): Filament\\Actions\\MountableAction->getForm()
#17 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(450): Filament\\Pages\\BasePage->getMountedActionForm()
#18 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(236): Filament\\Pages\\BasePage->Filament\\Actions\\Concerns\\{closure}()
#19 /home/rdp77/Projects/laravel-filament/vendor/filament/forms/src/Concerns/InteractsWithForms.php(311): value()
#20 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(448): Filament\\Pages\\BasePage->cacheForm()
#21 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(179): Filament\\Pages\\BasePage->cacheMountedActionForm()
#22 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Pages\\BasePage->mountAction()
#23 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#27 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(474): Livewire\\Wrapped->__call()
#28 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(101): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#29 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/LivewireManager.php(97): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#30 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(94): Livewire\\LivewireManager->update()
#31 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#32 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#33 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#34 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#35 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#36 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#38 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#40 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#42 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#44 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#45 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#47 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#49 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#51 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#52 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#53 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#54 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#55 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#56 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#58 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#60 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#62 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#64 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#66 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#68 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#70 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle()
#72 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#74 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#75 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle()
#76 /home/rdp77/Projects/laravel-filament/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#77 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(23): require_once('...')
#78 {main}

[previous exception] [object] (PDOException(code: 0): could not find driver at /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:66)
[stacktrace]
#0 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(66): PDO->__construct()
#1 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php(37): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(224): Illuminate\\Database\\Connectors\\SQLiteConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1231): call_user_func()
#6 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1267): Illuminate\\Database\\Connection->getPdo()
#7 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(512): Illuminate\\Database\\Connection->getReadPdo()
#8 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(812): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback()
#11 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run()
#12 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3132): Illuminate\\Database\\Connection->select()
#13 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3389): Illuminate\\Database\\Query\\Builder->runSelect()
#14 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3705): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#15 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3385): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#16 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(939): Illuminate\\Database\\Query\\Builder->pluck()
#17 /home/rdp77/Projects/laravel-filament/vendor/tomatophp/filament-icons/src/Components/IconPicker.php(21): Illuminate\\Database\\Eloquent\\Builder->pluck()
#18 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Components/ComponentManager.php(102): TomatoPHP\\FilamentIcons\\Components\\IconPicker->setUp()
#19 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Concerns/Configurable.php(22): Filament\\Support\\Components\\ComponentManager->configure()
#20 /home/rdp77/Projects/laravel-filament/vendor/filament/forms/src/Components/Field.php(27): Filament\\Support\\Components\\Component->configure()
#21 /home/rdp77/Projects/laravel-filament/vendor/tomatophp/filament-media-manager/src/Resources/FolderResource.php(85): Filament\\Forms\\Components\\Field::make()
#22 /home/rdp77/Projects/laravel-filament/vendor/filament/filament/src/Resources/Pages/ListRecords.php(99): TomatoPHP\\FilamentMediaManager\\Resources\\FolderResource::form()
#23 /home/rdp77/Projects/laravel-filament/vendor/filament/filament/src/Resources/Pages/ListRecords.php(115): Filament\\Resources\\Pages\\ListRecords->form()
#24 /home/rdp77/Projects/laravel-filament/vendor/filament/support/src/Concerns/EvaluatesClosures.php(35): Filament\\Resources\\Pages\\ListRecords->Filament\\Resources\\Pages\\{closure}()
#25 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/HasForm.php(55): Filament\\Support\\Components\\Component->evaluate()
#26 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(286): Filament\\Actions\\MountableAction->getForm()
#27 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(450): Filament\\Pages\\BasePage->getMountedActionForm()
#28 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(236): Filament\\Pages\\BasePage->Filament\\Actions\\Concerns\\{closure}()
#29 /home/rdp77/Projects/laravel-filament/vendor/filament/forms/src/Concerns/InteractsWithForms.php(311): value()
#30 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(448): Filament\\Pages\\BasePage->cacheForm()
#31 /home/rdp77/Projects/laravel-filament/vendor/filament/actions/src/Concerns/InteractsWithActions.php(179): Filament\\Pages\\BasePage->cacheMountedActionForm()
#32 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Pages\\BasePage->mountAction()
#33 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#35 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#36 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#37 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(474): Livewire\\Wrapped->__call()
#38 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(101): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#39 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/LivewireManager.php(97): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#40 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(94): Livewire\\LivewireManager->update()
#41 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#42 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#43 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#44 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#45 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#46 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#48 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#50 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#52 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#54 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#55 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#57 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#59 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#61 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#62 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#63 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#64 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#65 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#66 /home/rdp77/Projects/laravel-filament/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#68 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#70 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#72 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#76 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#78 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#80 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle()
#82 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#84 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#85 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle()
#86 /home/rdp77/Projects/laravel-filament/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#87 /home/rdp77/Projects/laravel-filament/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(23): require_once('...')
#88 {main}
"} 
~~~

![image](https://github.com/user-attachments/assets/8975fc2e-cbea-4b30-89f0-bbfe8fc547af)

**Comment by rdp77** [comment]
Related Issue: https://github.com/tomatophp/filament-icons/issues/2

**Comment by 3x1io** [comment]
publish filament-icons config and then make `"cache" => false` or just make sure you have sqlite3 ex of php
